project:
  type: website

website:
  title: "Ravi Verma"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Ravi Verma"
    right:
      - icon: github
        href: https://github.com/rverma213/
      - icon: twitter
        href: https://twitter.com/Raviii_Verma
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

